INSERT INTO users (username, password, role)
VALUES ('admin', '$2a$12$PUEz62.Y/3Et/HzaQ/WESeC8qou7GSmbL.C1ey9WBy9RgpIr/uagW', 'ADMIN');

INSERT INTO users (username, password, role)
VALUES ('user', '$2a$12$PUEz62.Y/3Et/HzaQ/WESeC8qou7GSmbL.C1ey9WBy9RgpIr/uagW', 'USER');

INSERT INTO tourist_attractions (rating, city, name, price, region, category, description)
VALUES

    (4.8, 'Praha', 'Karlův most', '$', 'Hlavní město Praha', 'Historické památky', 'Most přes řeku Vltavu v centru Prahy, spojující Staré Město s Malou Stranou. Jedná se o jeden z nejznámějších symbolů Prahy, zdobený sochami a oblíbený turistický cíl.'),
    (4.6, 'Kutná Hora', 'Chrám sv. Barbory', '$$', 'Středočeský kraj', 'Sakrální památky', 'Gotická katedrála v Kutné Hoře, zapsaná na seznamu světového dědictví UNESCO. Monumentální stavba zasvěcená svaté Barboře.'),
    (4.5, 'Karlovy Vary', 'Vřídlo', '$$$', 'Karlovarský kraj', 'Přírodní památky', 'Nejznámější minerální pramen v Karlových Varech. Tato termální pramen pochází z hloubky 2 000 metrů a vyvěrá zemským teplem.'),
    (4.1, 'Plzeň', 'Plzeňský Prazdroj', '$$', 'Plzeňský kraj', 'Interaktivní zážitky', 'Největší pivovar v České republice, kde je možné absolvovat prohlídku s ochutnávkou piva.'),
    (3.7, 'Český Krumlov', 'Zámek Český Krumlov', '$$$', 'Jihočeský kraj', 'Zámky a zahrady', 'Renesanční zámek UNESCO v Českém Krumlově, který je obklopen malebným parkem a historickými zahradami.'),
    (4.2, 'Karlovy Vary', 'Vřídlo', '$$$', 'Karlovarský kraj', 'Přírodní památky', 'Nejznámější minerální pramen v Karlových Varech. Tato termální pramen pochází z hloubky 2 000 metrů a vyvěrá zemským teplem.'),
    (3.9, 'Brno', 'Vila Tugendhat', '$$$$', 'Jihomoravský kraj', 'Architektonické skvosty', 'Funkcionalistická vila v Brně, navržená německým architektem Ludwigem Miesem van der Rohe.'),
    (4.6, 'Český ráj', 'Prachovské skály', '$$', 'Liberecký kraj', 'Přírodní památky', 'Skalní město v Českém ráji s úchvatnými skalními útvary a vyhlídkami.'),
    (4.1, 'České Budějovice', 'Černá věž', '$', 'Jihočeský kraj', 'Historické památky', 'Symbol města České Budějovice, gotická věž sloužící k obraně města.'),
    (4.7, 'Karlovy Vary', 'Diana Lookout Tower', '$$', 'Karlovarský kraj', 'Přírodní památky', 'Výhledová věž s panoramatickým výhledem na město Karlovy Vary a okolní krajinu.'),
    (4.3, 'Plzeň', 'Katedrála svatého Bartoloměje', '$', 'Plzeňský kraj', 'Sakrální památky', 'Gotická katedrála v Plzni, významné sakrální místo města.'),
    (4.5, 'Brno', 'Zoologická zahrada Brno', '$$', 'Jihomoravský kraj', 'Zoologické zahrady', 'Zoologická zahrada s bohatou kolekcí zvířat z celého světa.'),
    (4.8, 'Praha', 'Pražská orloj', '$$', 'Hlavní město Praha', 'Historické památky', 'Astronomický hodinový stroj umístěný na Staroměstském náměstí v Praze.'),
    (3.6, 'Kroměříž', 'Zahrady Kroměřížského zámku', '$$', 'Zlínský kraj', 'Zámky a zahrady', 'Barokní zahrady kolem Kroměřížského zámku, zapsané na seznamu světového dědictví UNESCO.'),
    (4.7, 'Český Krumlov', 'Kostel sv. Víta', '$', 'Jihočeský kraj', 'Sakrální památky', 'Gotický kostel v Českém Krumlově s bohatou historií a uměleckými poklady.'),
    (4.4, 'Karlovy Vary', 'Muzeum skla', '$$', 'Karlovarský kraj', 'Muzea a galerie', 'Muzeum zaměřené na historii sklářství v Karlových Varech.'),
    (2.3, 'Praha', 'Letenské sady', '$', 'Hlavní město Praha', 'Přírodní památky', 'Veřejný park s výhledem na historické centrum Prahy a řeku Vltavu.'),
    (4.1, 'Liberec', 'Zoo Liberec', '$$', 'Liberecký kraj', 'Zoologické zahrady', 'Zoologická zahrada v Liberci s rozsáhlou sbírkou exotických zvířat.'),
    (4.9, 'Brno', 'Brněnský závodní okruh', '$$', 'Jihomoravský kraj', 'Sportovní atrakce', 'Závodní okruh v Brně, pořádající mezinárodní motorsportové události.'),
    (4.7, 'Karlovy Vary', 'Vojenské lázně', '$$$', 'Karlovarský kraj', 'Lázně', 'Historické lázně v Karlových Varech, nabízející léčebné procedury a relaxaci.'),
    (4.2, 'Praha', 'Národní divadlo', '$$$', 'Hlavní město Praha', 'Kulturní instituce', 'Jedno z nejprestižnějších divadel v České republice, sídlo českého národního umění.'),
    (4.5, 'České Budějovice', 'Náměstí Přemysla Otakara II.', '$', 'Jihočeský kraj', 'Historické památky', 'Hlavní náměstí v Českých Budějovicích s historickými budovami a kašnou.'),
    (3.9, 'Karlovy Vary', 'Zámecké schody', '$', 'Karlovarský kraj', 'Historické památky', 'Historické schody vedoucí k Diana Lookout Tower v Karlových Varech.'),
    (4.3, 'Brno', 'Hrad Veveří', '$$', 'Jihomoravský kraj', 'Zámky a zahrady', 'Gotický hrad Veveří poblíž Brna, ležící na břehu Brněnské přehrady.'),
    (4.6, 'Olomouc', 'Sloup Nejsvětější Trojice', '$', 'Olomoucký kraj', 'Historické památky', 'Barokní sloup v Olomouci zasvěcený Nejsvětější Trojici.'),
    (4.0, 'Pardubice', 'Kunětická hora', '$$', 'Pardubický kraj', 'Přírodní památky', 'Vrcholová hora poblíž Pardubic s archeologickými nálezy a výhledem na okolní krajinu.'),
    (4.8, 'Kutná Hora', 'Kostel sv. Jakuba', '$$', 'Středočeský kraj', 'Sakrální památky', 'Gotický kostel sv. Jakuba v Kutné Hoře, zapsaný na seznamu světového dědictví UNESCO.'),
    (4.4, 'Český Krumlov', 'Muzeum moldavitu', '$$', 'Jihočeský kraj', 'Muzea a galerie', 'Muzeum v Českém Krumlově zaměřené na místní mineralogii a výrobu šperků z moldavitu.'),
    (4.7, 'Plzeň', 'Historické podzemí Plzně', '$$', 'Plzeňský kraj', 'Historické památky', 'Prohlídková trasa v podzemí Plzně, která nabízí pohled do historie města.'),
    (4.1, 'Třebíč', 'Bazilika sv. Prokopa', '$$', 'Kraj Vysočina', 'Sakrální památky', 'Románská bazilika v Třebíči, zapsaná na seznamu světového dědictví UNESCO.'),
    (4.9, 'Brno', 'Moravská galerie v Brně', '$$', 'Jihomoravský kraj', 'Muzea a galerie', 'Muzeum v Brně s bohatou sbírkou výtvarného umění a uměleckých děl.'),
    (4.3, 'Hradec Králové', 'Velké náměstí', '$', 'Královéhradecký kraj', 'Historické památky', 'Centrální náměstí v Hradci Králové s historickými budovami a Dominikánským klášterem.'),
    (4.6, 'Český Krumlov', 'Regionální muzeum v Českém Krumlově', '$$', 'Jihočeský kraj', 'Muzea a galerie', 'Muzeum v Českém Krumlově s expozicemi věnovanými historii města a regionu.'),
    (4.8, 'Karlovy Vary', 'Grandhotel Pupp', '$$$$', 'Karlovarský kraj', 'Luxusní hotely', 'Historický luxusní hotel v Karlových Varech, hostící významné osobnosti a filmové festivaly.'),
    (4.2, 'Praha', 'Katedrála sv. Víta', '$$', 'Hlavní město Praha', 'Sakrální památky', 'Gotická katedrála na Pražském hradě, symbol českého národního křesťanství.'),
    (4.5, 'Kroměříž', 'Zámek Kroměříž', '$$', 'Zlínský kraj', 'Zámky a zahrady', 'Barokní zámek v Kroměříži s unikátní zahradou, zapsaný na seznamu světového dědictví UNESCO.'),
    (4.0, 'Olomouc', 'Radnice v Olomouci', '$', 'Olomoucký kraj', 'Historické památky', 'Historická radnice v centru Olomouce s hodinami a věží.'),
    (4.7, 'Pardubice', 'Zámek Pardubice', '$$', 'Pardubický kraj', 'Zámky a zahrady', 'Renesanční zámek v Pardubicích s expozicemi věnovanými historii města.'),
    (4.1, 'Třebíč', 'Židovská čtvrť v Třebíči', '$$', 'Kraj Vysočina', 'Historické památky', 'Unikátní židovská čtvrť v Třebíči, zapsaná na seznamu světového dědictví UNESCO.'),
    (4.4, 'Hradec Králové', 'Bílá věž', '$', 'Královéhradecký kraj', 'Historické památky', 'Gotická věž v Hradci Králové, která sloužila k obraně města.'),
    (4.7, 'Lednice', 'Lednicko-valtický areál', '$$$', 'Jihomoravský kraj', 'Kulturní dědictví UNESCO', 'Rozlehlý komplex zámků, parků a umělých vodních ploch v Lednici a Valticích, zapsaný na seznamu světového dědictví UNESCO.'),
    (4.6, 'Telč', 'Historické centrum Telče', '$$', 'Kraj Vysočina', 'Kulturní dědictví UNESCO', 'Malebné historické centrum Telče s renesančními domy, zapsané na seznamu světového dědictví UNESCO.'),
    (4.8, 'Hřensko', 'Pravčická brána', '$$', 'Ústecký kraj', 'Přírodní památky', 'Největší přírodní skalní most v Evropě, nacházející se v Českém Švýcarsku.'),
    (4.5, 'Macocha', 'Punkevní jeskyně a Macocha', '$$', 'Jihomoravský kraj', 'Přírodní památky', 'Komplex jeskyní a propasti v Moravském krasu, známý svou přírodní krásou.'),
    (4.9, 'Karlštejn', 'Hrad Karlštejn', '$$$', 'Středočeský kraj', 'Historické památky', 'Gotický hrad založený Karlem IV. jako úložiště korunovačních klenotů a svatých relikvií.'),
    (4.4, 'Brno', 'Hrad Špilberk', '$$', 'Jihomoravský kraj', 'Historické památky', 'Gotický hrad v Brně, sloužící v minulosti jako pevnost a vězení.'),
    (4.7, 'Ostrava', 'Dolní oblast Vítkovice', '$$', 'Moravskoslezský kraj', 'Industriální památky', 'Komplex průmyslových budov v Ostravě, dříve sloužící k těžbě a zpracování železa.'),
    (4.8, 'Dvůr Králové nad Labem', 'Zoo Dvůr Králové', '$$', 'Královéhradecký kraj', 'Zoologické zahrady', 'Zoologická zahrada se specializací na chov afrických savců a jejich ochranu v přírodě.'),
    (4.6, 'Praha', 'Botanická zahrada Praha', '$$', 'Hlavní město Praha', 'Botanické zahrady', 'Botanická zahrada v Troji s rozsáhlou sbírkou rostlin z různých částí světa.'),
    (4.5, 'Koněprusy', 'Koněpruské jeskyně', '$$', 'Středočeský kraj', 'Přírodní památky', 'Jeskynní systém s unikátními krápníkovými útvary a podzemními jezírky v blízkosti Karlštejna.'),
    (4.4, 'Mikulov', 'Svatý Kopeček', '$$', 'Jihomoravský kraj', 'Náboženská místa', 'Poutní místo u Mikulova s kostelem Nanebevzetí Panny Marie a poutní kaplí svatého Šebestiána.'),
    (4.2, 'Český Krumlov', 'Vltavský luh', '$', 'Jihočeský kraj', 'Přírodní památky', 'Přírodní rezervace na březích řeky Vltavy poblíž Českého Krumlova s rozmanitou faunou a flórou.'),
    (4.8, 'Praha', 'Petřínská rozhledna', '$$', 'Hlavní město Praha', 'Historické památky', 'Rozhledna na Petříně, nabízející panoramatický výhled na Prahu.'),
    (4.0, 'Liberec', 'Ještěd', '$$', 'Liberecký kraj', 'Přírodní památky', 'Dominantní hora v Libereckých horách s rozhlednou a televizní věží.'),
    (4.3, 'Ostrava', 'Zoo Ostrava', '$$', 'Moravskoslezský kraj', 'Zoologické zahrady', 'Zoologická zahrada v Ostravě s expozicemi zvířat z různých částí světa.'),
    (4.1, 'Kutná Hora', 'Ossuary', '$', 'Středočeský kraj', 'Historické památky', 'Kostnice v Kutné Hoře s unikátní výzdobou z lidských kostí.'),
    (4.7, 'Praha', 'Národní galerie v Praze', '$$', 'Hlavní město Praha', 'Muzea a galerie', 'Muzeum v Praze s bohatou sbírkou evropského výtvarného umění.'),
    (4.2, 'Český Krumlov', 'Lipno', '$$', 'Jihočeský kraj', 'Přírodní památky', 'Přehrada na řece Vltavě poblíž Českého Krumlova, oblíbené rekreační místo pro vodní sporty.'),
    (4.8, 'Plzeň', 'Pivovar Pilsner Urquell', '$$', 'Plzeňský kraj', 'Interaktivní zážitky', 'Muzeum pivovarnictví v Plzni, domov piva Pilsner Urquell.'),
    (4.6, 'Karlovy Vary', 'Becherovka Visitor Center', '$$', 'Karlovarský kraj', 'Interaktivní zážitky', 'Centrum pro návštěvníky, kde je možné dozvědět se o historii a výrobě Becherovky.'),
    (4.4, 'Olomouc', 'Arboretum', '$', 'Olomoucký kraj', 'Botanické zahrady', 'Botanická zahrada v Olomouci s rozsáhlou sbírkou rostlin z různých částí světa.'),
    (4.9, 'České Budějovice', 'Výstaviště České Budějovice', '$', 'Jihočeský kraj', 'Kulturní instituce', 'Výstaviště v Českých Budějovicích, pořádající veletrhy a kulturní akce.'),
    (4.5, 'Kroměříž', 'Arcibiskupský zámek Kroměříž', '$$', 'Zlínský kraj', 'Zámky a zahrady', 'Barokní zámek v Kroměříži, sídlo arcibiskupa olomouckého.'),
    (4.3, 'Pardubice', 'Lázně Bohdaneč', '$$$', 'Pardubický kraj', 'Lázně', 'Lázně v Pardubicích nabízející lázeňské procedury a wellness služby.'),
    (4.7, 'Třebíč', 'Zámek Třebíč', '$$', 'Kraj Vysočina', 'Zámky a zahrady', 'Zámek v Třebíči s renesančním palácem a francouzskými zahradami.'),
    (4.2, 'Hradec Králové', 'Muzeum Východních Čech', '$', 'Královéhradecký kraj', 'Muzea a galerie', 'Muzeum v Hradci Králové se zaměřením na regionální historii a kulturu.'),
    (4.8, 'Lednice', 'Zámecký park Lednice', '$$', 'Jihomoravský kraj', 'Zámky a zahrady', 'Rozsáhlý park v Lednici s exotickými rostlinami a romantickými stavbami.'),
    (4.4, 'Telč', 'Zámek Telč', '$$', 'Kraj Vysočina', 'Zámky a zahrady', 'Renesanční zámek v Telči s unikátní zámeckou zahradou a výstavními sály.'),
    (4.3, 'Hřensko', 'Divoká soutěska', '$', 'Ústecký kraj', 'Přírodní památky', 'Úzká soutěska na řece Kamenici s divokými skalními útvary a vodopády.'),
    (4.6, 'Macocha', 'Jeskyně Punkva', '$$', 'Jihomoravský kraj', 'Přírodní památky', 'Jeskyně v Moravském krasu s podzemní řekou a nádhernými krápníkovými útvary.'),
    (4.9, 'Karlštejn', 'Velká věž Karlštejn', '$$', 'Středočeský kraj', 'Historické památky', 'Nejvyšší věž hradu Karlštejn s úchvatným výhledem do okolní krajiny.'),
    (4.3, 'Brno', 'Botanická zahrada Brno', '$', 'Jihomoravský kraj', 'Botanické zahrady', 'Botanická zahrada v Brně s rozsáhlou sbírkou rostlin z celého světa.'),
    (4.1, 'Kutná Hora', 'Barborská třída', '$$', 'Středočeský kraj', 'Historické památky', 'Historická ulice v Kutné Hoře s renesančními a barokními domy.'),
    (4.7, 'Praha', 'Národní muzeum', '$$', 'Hlavní město Praha', 'Muzea a galerie', 'Národní muzeum v Praze s bohatými sbírkami přírodnin, umění a historie.'),
    (4.5, 'Brno', 'Zelný trh', '$', 'Jihomoravský kraj', 'Historické památky', 'Historické náměstí v Brně s kašnou a barokními domy.'),
    (4.2, 'Český Krumlov', 'Muzeum voskových figurín', '$', 'Jihočeský kraj', 'Muzea a galerie', 'Muzeum v Českém Krumlově s expozicemi voskových figurín.'),
    (4.8, 'Plzeň', 'Techmania Science Center', '$$', 'Plzeňský kraj', 'Interaktivní zážitky', 'Vědecké centrum v Plzni s interaktivními expozicemi a experimenty pro děti i dospělé.'),
    (4.6, 'Karlovy Vary', 'Lázeňská ulice', '$$', 'Karlovarský kraj', 'Historické památky', 'Centrální lázeňská ulice v Karlových Varech s lázeňskými domy a restauracemi.'),
    (4.4, 'Olomouc', 'Moravské divadlo', '$$', 'Olomoucký kraj', 'Kulturní instituce', 'Divadelní instituce v Olomouci, provozující divadelní představení a koncerty.'),
    (4.9, 'České Budějovice', 'Černá věž', '$$', 'Jihočeský kraj', 'Historické památky', 'Gotická věž v Českých Budějovicích s výhledem na historické centrum města.'),
    (4.5, 'Kroměříž', 'Zahrada kláštera Kroměříž', '$', 'Zlínský kraj', 'Zámky a zahrady', 'Renesanční zahrada při klášteře v Kroměříži s fontánami a sochami.'),
    (4.3, 'Pardubice', 'Historické centrum Pardubic', '$', 'Pardubický kraj', 'Historické památky', 'Středověké centrum Pardubic s renesanční radnicí a historickými domy.'),
    (4.7, 'Třebíč', 'Zámecká zahrada v Třebíči', '$$', 'Kraj Vysočina', 'Zámky a zahrady', 'Zámecká zahrada v Třebíči s terasovitými záhony a výhledem na město.'),
    (4.2, 'Hradec Králové', 'Velké náměstí', '$', 'Královéhradecký kraj', 'Historické památky', 'Centrální náměstí v Hradci Králové s historickými budovami a kašnou.'),
    (4.8, 'Lednice', 'Zámecká galerie Lednice', '$$', 'Jihomoravský kraj', 'Zámky a zahrady', 'Galerie v Lednici s expozicemi uměleckých děl a historickými artefakty.'),
    (4.4, 'Telč', 'Zámecká věž Telč', '$$', 'Kraj Vysočina', 'Historické památky', 'Zámecká věž v Telči s vyhlídkou na historické centrum města.'),
    (4.3, 'Hřensko', 'Přírodní divadlo', '$$', 'Ústecký kraj', 'Přírodní památky', 'Skalní divadlo v Hřensku s přírodní scénou na břehu řeky Kamenice.'),
    (4.6, 'Macocha', 'Amfiteátr Macocha', '$$', 'Jihomoravský kraj', 'Přírodní památky', 'Přírodní amfiteátr poblíž Macochy, obklopený vysokými skalními stěnami.'),
    (4.9, 'Karlštejn', 'Kostnice', '$', 'Středočeský kraj', 'Historické památky', 'Kostnice v Karlštejně s unikátní výzdobou z lidských kostí.'),
    (4.3, 'Brno', 'Moravské zemské muzeum - Dietrichsteinský palác', '$$', 'Jihomoravský kraj', 'Muzea a galerie', 'Dietrichsteinský palác v Brně, sídlo Moravského zemského muzea.'),
    (4.1, 'Kutná Hora', 'Vlašský dvůr', '$$', 'Středočeský kraj', 'Historické památky', 'Gotický palác v Kutné Hoře, sloužící jako obchodní a obytný dům.'),
    (4.7, 'Praha', 'Národní technické muzeum', '$$', 'Hlavní město Praha', 'Muzea a galerie', 'Muzeum v Praze s expozicemi věnovanými technickému a průmyslovému dědictví.'),
    (4.5, 'Brno', 'ZOO Brno', '$$', 'Jihomoravský kraj', 'Zoologické zahrady', 'Zoologická zahrada v Brně s rozsáhlou sbírkou zvířat z celého světa.'),
    (4.2, 'Český Krumlov', 'Muzeum tortur', '$', 'Jihočeský kraj', 'Muzea a galerie', 'Muzeum v Českém Krumlově s expozicemi mučících nástrojů a popravčích metod.'),
    (4.8, 'Plzeň', 'Katedrála sv. Bartoloměje', '$$', 'Plzeňský kraj', 'Sakrální památky', 'Gotická katedrála v Plzni s významnou sochařskou výzdobou.'),
    (4.6, 'Karlovy Vary', 'Dům zahraničních slavností', '$$', 'Karlovarský kraj', 'Historické památky', 'Historický dům v Karlových Varech, místo konání filmového festivalu.'),
    (4.4, 'Olomouc', 'Olomoucký hrad', '$$', 'Olomoucký kraj', 'Historické památky', 'Gotický hrad v Olomouci s kaplí a vyhlídkovou věží.'),
    (4.9, 'České Budějovice', 'Jihočeské muzeum v Českých Budějovicích', '$$', 'Jihočeský kraj', 'Muzea a galerie', 'Muzeum v Českých Budějovicích s expozicemi archeologie, historie a umění.'),
    (4.5, 'Kroměříž', 'Zámecká věž Kroměříž', '$$', 'Zlínský kraj', 'Historické památky', 'Zámecká věž v Kroměříži s výhledem na historické centrum města.'),
    (4.3, 'Pardubice', 'Historické podzemí Pardubic', '$$', 'Pardubický kraj', 'Historické památky', 'Prohlídkové podzemí v Pardubicích s expozicemi týkajícími se historie města.'),
    (4.7, 'Třebíč', 'Muzeum Vysočiny Třebíč', '$$', 'Kraj Vysočina', 'Muzea a galerie', 'Muzeum v Třebíči s expozicemi archeologie, historie a umění regionu.'),
    (4.2, 'Hradec Králové', 'Bílé náměstí', '$', 'Královéhradecký kraj', 'Historické památky', 'Náměstí v Hradci Králové s barokními kašnami a historickými domy.'),
    (4.8, 'Lednice', 'Minaret Lednice', '$$', 'Jihomoravský kraj', 'Historické památky', 'Minaret v Lednici, součást zámeckého parku a romantické krajiny Lednicko-valtického areálu.'),
    (4.4, 'Telč', 'Telčská radnice', '$$', 'Kraj Vysočina', 'Historické památky', 'Renesanční radnice v Telči s věží a hodinami.'),
    (4.3, 'Hřensko', 'Gabrielina stezka', '$', 'Ústecký kraj', 'Turistické atrakce', 'Turistická stezka vedoucí po břehu řeky Kamenice v Hřensku.'),
    (4.6, 'Macocha', 'Macocha Abyss', '$$', 'Jihomoravský kraj', 'Přírodní památky', 'Propast Macocha v Moravském krasu, jedna z nejhlubších jeskynních propastí v Česku.'),
    (4.9, 'Karlštejn', 'Karlštejnská kasemat', '$$', 'Středočeský kraj', 'Historické památky', 'Podzemní chodby a sklepení hradu Karlštejn sloužící jako úkryt a zbrojnice.'),
    (4.3, 'Brno', 'Moravské galerie', '$$', 'Jihomoravský kraj', 'Muzea a galerie', 'Soubor galerií v Brně s expozicemi výtvarného umění a uměleckých děl.'),
    (4.1, 'Kutná Hora', 'Kutnohorský důl', '$$', 'Středočeský kraj', 'Historické památky', 'Stříbrný důl v Kutné Hoře s expozicí týkající se těžby stříbra.'),
    (4.7, 'Praha', 'Výstaviště Holešovice', '$$', 'Hlavní město Praha', 'Kulturní instituce', 'Výstaviště v pražských Holešovicích pořádající veletrhy, koncerty a kulturní akce.'),
    (4.5, 'Brno', 'Katedrála svatého Petra a Pavla', '$$', 'Jihomoravský kraj', 'Sakrální památky', 'Gotická katedrála v Brně, největší kostel na území Moravy.'),
    (4.2, 'Český Krumlov', 'Plátenická stoka', '$', 'Jihočeský kraj', 'Historické památky', 'Středověká kanalizační stoka v Českém Krumlově, která sloužila k odvádění odpadních vod.'),
    (4.8, 'Plzeň', 'Kostel sv. Bartoloměje', '$$', 'Plzeňský kraj', 'Sakrální památky', 'Gotický kostel v Plzni s unikátní architekturou a výzdobou.');
